## common variables
# substitutions:
#   foo: bar

esphome:
  name: radio-gateway
  # platformio_options:
  #   board_build.f_flash: 40000000L
  #   board_build.flash_mode: dio

esp32:
  # TODO: migrate to vanilla ESP32
  board: lolin_c3_mini
  variant: esp32c3
  framework:
    type: arduino
    # version: "5.1.2"
    # # Custom sdkconfig options
    # sdkconfig_options:
    #   CONFIG_ESPTOOLPY_OCT_FLASH: y

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.33
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 192.168.1.4
  domain: .home
  # output_power: 8.5
  # fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHomeRadioGateway"
    password: !secret ap_password

captive_portal:

###############
### DEVICES ###
###############
esp32_ble_tracker:
sensor:
binary_sensor:
  - platform: xiaomi_mjyd02yla
    name: "MJYD02YL-A Night Light"
    mac_address: "CC:B5:D1:B9:C2:65"
    bindkey: !secret xiaomi_mjyd02yla_bindkey
    idle_time:
      name: "MJYD02YL-A Idle Time"
    light:
      name: "MJYD02YL-A Light Status"
    battery_level:
      name: "MJYD02YL-A Battery Level"
    illuminance:
      name: "MJYD02YL-A Illuminance"
